In [1]:
import pandas as pd 
import numpy as np

In [2]:
_values = [
    [1, 2, np.nan, 4, 5], 
    [1, np.nan, 3, 4, 5], 
    [1, 2, 3, 4, np.nan]
]
_cols = ['a', 'b', 'c', 'd', 'e']

df = pd.DataFrame(_values, columns = _cols)

df

   a    b    c  d    e
0  1  2.0  NaN  4  5.0
1  1  NaN  3.0  4  5.0
2  1  2.0  3.0  4  NaN

In [4]:
# 일반적으로 결측의 연산은 되지 않는다. -> 결과는 nan 고정 
3 * np.nan

nan

In [ ]:
# 결측치 == 결측치 ??? -> False -> 연산이 성립 되지 않기때문에 
np.nan == np.nan

False

In [6]:
# pandas의 데이터프레임이나 스리즈 연산에서는 결측치를 제외하고 연산이 가능
df.sum()

a     3.0
b     4.0
c     6.0
d    12.0
e    10.0
dtype: float64

In [7]:
# 데이터프레임에서 결측치가 존재하는가?
# 존재 유무 ( is ) + 결측치 ( na ) -> isna() 함수 
# 해당 함수를 사용하는 이유는 결측치와 결측치를 '같다' 비교연산자로 True 나오지 않기 때문에 
df.isna()

       a      b      c      d      e
0  False  False   True  False  False
1  False   True  False  False  False
2  False  False  False  False   True

In [8]:
# 데이터프레임에 비교연산자를 사용하면 결과? 
df == 1

      a      b      c      d      e
0  True  False  False  False  False
1  True  False  False  False  False
2  True  False  False  False  False

In [ ]:
# isna() 함수를 이용하면 결측치와 같은가? T/F로 이루어진 데이터프레임 생성 
# 결측치의 개수를 확인하려면? -> bool의 values를 합계를 구한다. 
# sum() -> 기본적(특정 매개변수에 기본값이 존재)으로 컬럼을 기준으로 합산 
df.isna().sum()

a    0
b    1
c    1
d    0
e    1
dtype: int64

In [12]:
# sum() 함수는 axis 매개변수가 존재 
# 0 | 1 ,  'index' | 'columns'
df.isna().sum(axis = 'columns')

0    1
1    1
2    1
dtype: int64

In [13]:
# 외부의 파일을 로드하고 해당 데이터프레임의 정보를 확인하는 함수 
# info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int64
 1   b       2 non-null      float64
 2   c       2 non-null      float64
 3   d       3 non-null      int64
 4   e       2 non-null      float64
dtypes: float64(3), int64(2)
memory usage: 252.0 bytes

In [14]:
df

   a    b    c  d    e
0  1  2.0  NaN  4  5.0
1  1  NaN  3.0  4  5.0
2  1  2.0  3.0  4  NaN

In [16]:
# 결측치의 제거 
# 1. 결측치가 포함되어 있는 컬럼을 제거
    # 해당 컬럼을 사용하지 않는 경우 
# 2. 결측치가 포함되어 있는 인덱스를 제거 
    # 해당 인덱스의 신뢰도 떨어질때 
    # 제거하는 데이터의 갯수가 많은 경우? -> 선택 
# 결측치( na ) , 제거한다( drop )
# dropna()
    # 매개변수 axis -> 0 'index' | 1 'columns' (기본값은 0)
    # 매개변수 inplace -> 기본값 False -> 원본 데이터(class 안에 저장되어있는 데이터)를 
    #                                   변경할지 지정
df.dropna(axis=1)

   a  d
0  1  4
1  1  4
2  1  4

In [18]:
# 결측치가 포함되어 있는 행인가? 열인가? 판단하는 방법 
# any() -> 매개변수 axis 0 | 1
df.isna().any(axis = 1)

0    True
1    True
2    True
dtype: bool

In [19]:
# 결측치에 특정 데이터를 채운다. 
# 채운다(fill) + 결측치(na)
# fillna()
    # 첫번째 인자에 특정 데이터를 입력하면 -> 결측치에 해당 데이터가 채워진다.
    # 첫번째 인자에 값을 채우지 않고 method 매개변수를 이용
        # 'ffill' / 'bfill'
            # ffill -> 전 인덱스의 데이터로 채워준다.
            # bfill -> 후 인덱스의 데이터로 채워준다.
df.fillna(method='ffill')

C:\Users\ekfla\AppData\Local\Temp\ipykernel_9644\1968569891.py:9: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

   a    b    c  d    e
0  1  2.0  NaN  4  5.0
1  1  2.0  3.0  4  5.0
2  1  2.0  3.0  4  5.0

In [20]:
df.fillna(method='bfill')

C:\Users\ekfla\AppData\Local\Temp\ipykernel_9644\2831856154.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

   a    b    c  d    e
0  1  2.0  3.0  4  5.0
1  1  2.0  3.0  4  5.0
2  1  2.0  3.0  4  NaN

In [23]:
# 특정 데이터 결측치 치환
df.fillna(10)

   a     b     c  d     e
0  1   2.0  10.0  4   5.0
1  1  10.0   3.0  4   5.0
2  1   2.0   3.0  4  10.0

In [25]:
# value, method 매개변수에 값을 입력하지 않으면 에러가 발생
# df.fillna()

#### 데이터프레임의 필터링 
- 데이터프레임명.loc[인덱스의 조건, 컬럼의 조건]
    - 인덱스의 값을 기준으로 필터 
    - 컬럼의 값을 기준으로 필터 
    - 시작 : 종료 -> 시작값부터 종료값까지 (종료가 포함)
- 데이터프레임명.iloc[인덱스의 위치, 컬럼의 위치]
    - 인덱스의 위치를 기준으로 필터
    - 컬럼의 위치를 기준으로 필터 
    - 시작 : 종료 -> 시작 위치부터 종료 위치 전까지 (종료위치가 미포함)
- 특정 컬럼의 데이터를 확인 
    - 데이터프레임명[ 컬럼의 값 ] -> 조건이 단일 타입(str, int)이라면 -> 결과는 Series
    - 데이터프레임명[ [컬럼의 값, ...] ] -> 조건이 단일 타입(tuple, list)이 아니라면 -> 결과는 DataFrame

In [1]:
import pandas as pd

In [3]:
df = pd.DataFrame({'price': [100, 250, 400, 150]})

# 가격에 단위를 붙이는 함수 적용
df['price_str'] = df['price'].map(lambda x: f"${x}")
print(df)

   price price_str
0    100      $100
1    250      $250
2    400      $400
3    150      $150

In [7]:
df = pd.DataFrame({'product': ['  iphone ', ' galaxy', 'pixel  ']})

# 문자열 공백 제거 (str.strip 메서드 활용)
# df['product'] = df['product'].map(str.strip)
df['product'] = df['product'].str.strip()
print(df)

  product
0  iphone
1  galaxy
2   pixel

In [11]:
import numpy as np

s = pd.Series(['cat', 'dog', np.nan, 'rabbit'])

# NaN을 무시하고 대문자로 변환
# ignore가 없으면 NaN에 upper()를 시도하다가 오류가 날 수 있음
# result = s.map(lambda x: x.upper(), na_action='ignore')
# print(result)
s.str.upper()

0       CAT
1       DOG
2       NaN
3    RABBIT
dtype: object

In [2]:
import pandas as pd

In [6]:
df = pd.read_excel("../csv/Superstore KR - VizLab 2022.xlsx")

In [7]:
df.head()

,Row ID,Order ID,Order Date,Delivery Date,Delivery Mode,Customer ID,Customer Name,Customer Segment,Country,Address Region,Address SD,Address SGG,Product ID,Product Name,Product Category,Product Sub-Category,Sales,Quantity,Discount,Profit
0,1,CA-2020-152156,2020-11-08,2020-11-11,빠른배송,CG-12520,류미령,개인고객,대한민국,호남,광주광역시,북구,FUR-BO-10001798,Bush Somerset Collection Bookcase,가구,책장,3.173645e+05,2,0.00,50778.3264
1,2,CA-2020-152156,2020-11-08,2020-11-11,빠른배송,CG-12520,류미령,개인고객,대한민국,호남,광주광역시,북구,FUR-CH-10000454,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",가구,의자,8.867453e+05,3,0.00,266023.5930
2,3,CA-2020-138688,2020-06-12,2020-06-16,빠른배송,DV-13045,문윤재,기업고객,대한민국,수도권,경기도,광명시,OFF-LA-10000240,Self-Adhesive Address Labels for Typewriters b...,사무용품,라벨류,1.771213e+04,2,0.00,8324.7011
3,4,US-2019-108966,2019-10-11,2019-10-18,일반배송,SO-20335,천경아,개인고객,대한민국,수도권,서울특별시,용산구,FUR-TA-10000577,Bretford CR4500 Series Slim Rectangular Table,가구,책상,1.160105e+06,5,0.45,-464042.0565
4,5,US-2019-108966,2019-10-11,2019-10-18,일반배송,SO-20335,천경아,개인고객,대한민국,수도권,서울특별시,용산구,OFF-ST-10000760,Eldon Fold 'N Roll Cart System,사무용품,수납제품,2.709883e+04,2,0.20,3048.6186

In [9]:
df1 =  df.loc[:, 'Row ID' : 'Customer ID']

In [13]:
df1['Order Date'] = pd.to_datetime(df1['Order Date'])
df1['Delivery Date'] = pd.to_datetime(df1['Delivery Date'])
df1['배송기간'] = df1['Delivery Date'] - df1['Order Date']
df1

,Row ID,Order ID,Order Date,Delivery Date,Delivery Mode,Customer ID,배송기간
0,1,CA-2020-152156,2020-11-08,2020-11-11,빠른배송,CG-12520,3 days
1,2,CA-2020-152156,2020-11-08,2020-11-11,빠른배송,CG-12520,3 days
2,3,CA-2020-138688,2020-06-12,2020-06-16,빠른배송,DV-13045,4 days
3,4,US-2019-108966,2019-10-11,2019-10-18,일반배송,SO-20335,7 days
4,5,US-2019-108966,2019-10-11,2019-10-18,일반배송,SO-20335,7 days
...,...,...,...,...,...,...,...
9989,9990,CA-2018-110422,2018-01-21,2018-01-23,빠른배송,TB-21400,2 days
9990,9991,CA-2021-121258,2021-02-26,2021-03-03,일반배송,DB-13060,5 days
9991,9992,CA-2021-121258,2021-02-26,2021-03-03,일반배송,DB-13060,5 days
9992,9993,CA-2021-121258,2021-02-26,2021-03-03,일반배송,DB-13060,5 days
9993,9994,CA-2021-119914,2021-05-04,2021-05-09,빠른배송,CC-12220,5 days

In [10]:
df2 = df.drop(
    ['Order ID', 'Order Date', 'Delivery Date', 'Delivery Mode', 'Customer ID'], axis=1
)
df2

,Row ID,Customer Name,Customer Segment,Country,Address Region,Address SD,Address SGG,Product ID,Product Name,Product Category,Product Sub-Category,Sales,Quantity,Discount,Profit
0,1,류미령,개인고객,대한민국,호남,광주광역시,북구,FUR-BO-10001798,Bush Somerset Collection Bookcase,가구,책장,3.173645e+05,2,0.00,50778.3264
1,2,류미령,개인고객,대한민국,호남,광주광역시,북구,FUR-CH-10000454,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",가구,의자,8.867453e+05,3,0.00,266023.5930
2,3,문윤재,기업고객,대한민국,수도권,경기도,광명시,OFF-LA-10000240,Self-Adhesive Address Labels for Typewriters b...,사무용품,라벨류,1.771213e+04,2,0.00,8324.7011
3,4,천경아,개인고객,대한민국,수도권,서울특별시,용산구,FUR-TA-10000577,Bretford CR4500 Series Slim Rectangular Table,가구,책상,1.160105e+06,5,0.45,-464042.0565
4,5,천경아,개인고객,대한민국,수도권,서울특별시,용산구,OFF-ST-10000760,Eldon Fold 'N Roll Cart System,사무용품,수납제품,2.709883e+04,2,0.20,3048.6186
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,허종수,개인고객,대한민국,영남,경상북도,영덕군,FUR-FU-10001889,Ultra Door Pull Handle,가구,가구소품,3.058795e+04,3,0.20,4970.5422
9990,9991,문율,개인고객,대한민국,수도권,경기도,평택시,FUR-FU-10000747,Tenex B1-RE Series Chair Mats for Low Pile Car...,가구,가구소품,1.114095e+05,2,0.00,18939.6218
9991,9992,문율,개인고객,대한민국,수도권,경기도,평택시,TEC-PH-10003645,Aastra 57i VoIP phone,전자제품,전화기,3.132648e+05,2,0.20,23494.8618
9992,9993,문율,개인고객,대한민국,수도권,경기도,평택시,OFF-PA-10004041,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",사무용품,종이류,3.586040e+04,4,0.00,16137.1800
9993,9994,노우석,개인고객,대한민국,수도권,서울특별시,구로구,OFF-AP-10002684,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",사무용품,집기비품,2.945883e+05,2,0.00,88376.5020

In [19]:
df2[['Address Region']].groupby(df1['배송기간']).count()

        Address Region
배송기간
0 days             519
1 days             369
2 days            1334
3 days            1005
4 days            2773
5 days            2170
6 days            1203
7 days             621