In [1]:
import pandas as pd 
from bs4 import BeautifulSoup as bs
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from sqlalchemy import create_engine

In [17]:
driver = webdriver.Chrome()

In [18]:
driver.get('https://comp.wisereport.co.kr/company/c1010001.aspx')

In [23]:
html_data = driver.page_source

In [24]:
soup = bs(html_data, 'html.parser')

In [25]:
div_list = soup.find_all(
    'div', 
    attrs = {
        'class' : 'fl_le'
    }
)

In [26]:
len(div_list)

5

In [39]:
list(
    map(
        lambda x : '주요지표' in x.get_text() or '어닝서프라이즈' in x.get_text(), 
        div_list
    )
)

[False, True, True, False, False]

In [50]:
pd.read_html(str(div_list[1]) )[0]

C:\Users\ekfla\AppData\Local\Temp\ipykernel_28940\2053644940.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(str(div_list[1]) )[0]

        주요지표   2025/12(A)     2026/12(E)    Fwd. 12M(E)
0        PER        33.37           5.96           5.55
1        PBR         3.42           2.21           1.94
2        PCR        17.31           4.98           4.68
3  EV/EBITDA        14.36           3.21           2.80
4        EPS       6,564원        36,745원        39,438원
5        BPS      63,997원        99,252원       113,104원
6     EBITDA  905,276.4억원  3,534,695.2억원  3,768,787.8억원
7      현금DPS       1,668원         3,292원         2,999원
8    현금배당수익률        0.76%          1.50%          1.37%
9       회계기준           연결             연결             연결

In [42]:
df1 = pd.read_html(str(div_list[1]))[0]
df1

C:\Users\ekfla\AppData\Local\Temp\ipykernel_28940\540314129.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df1 = pd.read_html(str(div_list[1]))[0]

        주요지표   2025/12(A)     2026/12(E)    Fwd. 12M(E)
0        PER        33.37           5.96           5.55
1        PBR         3.42           2.21           1.94
2        PCR        17.31           4.98           4.68
3  EV/EBITDA        14.36           3.21           2.80
4        EPS       6,564원        36,745원        39,438원
5        BPS      63,997원        99,252원       113,104원
6     EBITDA  905,276.4억원  3,534,695.2억원  3,768,787.8억원
7      현금DPS       1,668원         3,292원         2,999원
8    현금배당수익률        0.76%          1.50%          1.37%
9       회계기준           연결             연결             연결

In [51]:
df2 = pd.read_html(str(div_list[2]))[0]
df2

C:\Users\ekfla\AppData\Local\Temp\ipykernel_28940\3789423633.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df2 = pd.read_html(str(div_list[2]))[0]

,"어닝서프라이즈 * 단위: 억원, %","어닝서프라이즈 * 단위: 억원, %.1","어닝서프라이즈 * 단위: 억원, %.2","어닝서프라이즈 * 단위: 억원, %.3","어닝서프라이즈 * 단위: 억원, %.4"
0,재무연월,재무연월,2025/09,2025/12,2026/03
1,영업이익,컨센서스,101922.8,185098.0,401923.4
2,영업이익,잠정치,121000.0,200000.0,572000.0
3,영업이익,Surprise,18.72,8.05,42.32
4,영업이익,전분기대비보기전년동기대비,31.76,208.04,755.61
5,NaN,전분기대비,158.77,64.39,184.95
6,NaN,NaN,NaN,NaN,NaN
7,당기순이익,컨센서스,96001.6,163415.8,314258.0
8,당기순이익,잠정치,"● 120,064.0","● 192,920.0",NaN
9,당기순이익,Surprise,25.06,18.05,NaN
10,당기순이익,전분기대비보기전년동기대비,22.75,154.64,NaN
11,NaN,전분기대비,143.34,60.68,NaN
12,잠정치발표(예정)일/회계기준,잠정치발표(예정)일/회계기준,2025/10/14(연결),2026/01/08(연결),2026/04/07(연결)

In [53]:
# 인덱스 6 제거 
df2.drop(index=6, inplace=True)

In [58]:
df2.iloc[:, 0] = df2.iloc[:, 0].ffill()

In [61]:
df2.set_index([df2.columns[0], df2.columns[1]])

                                          어닝서프라이즈 * 단위: 억원, %.2  \
어닝서프라이즈 * 단위: 억원, % 어닝서프라이즈 * 단위: 억원, %.1
재무연월                재무연월                                2025/09
영업이익                컨센서스                               101922.8
                    잠정치                                121000.0
                    Surprise                              18.72
                    전분기대비보기전년동기대비                         31.76
                    전분기대비                                158.77
당기순이익               컨센서스                                96001.6
                    잠정치                             ● 120,064.0
                    Surprise                              25.06
                    전분기대비보기전년동기대비                         22.75
                    전분기대비                                143.34
잠정치발표(예정)일/회계기준     잠정치발표(예정)일/회계기준              2025/10/14(연결)

                                          어닝서프라이즈 * 단위: 억원, %.3  \
어닝서프라이즈 * 단위: 억원, % 어닝서프라이즈 * 단위: 억원, %.1
재무연월                재무연월                                2025/12
영업이익                컨센서스                               185098.0
                    잠정치                                200000.0
                    Surprise                               8.05
                    전분기대비보기전년동기대비                        208.04
                    전분기대비                                 64.39
당기순이익               컨센서스                               163415.8
                    잠정치                             ● 192,920.0
                    Surprise                              18.05
                    전분기대비보기전년동기대비                        154.64
                    전분기대비                                 60.68
잠정치발표(예정)일/회계기준     잠정치발표(예정)일/회계기준              2026/01/08(연결)

                                          어닝서프라이즈 * 단위: 억원, %.4
어닝서프라이즈 * 단위: 억원, % 어닝서프라이즈 * 단위: 억원, %.1
재무연월                재무연월                                2026/03
영업이익                컨센서스                               401923.4
                    잠정치                                572000.0
                    Surprise                              42.32
                    전분기대비보기전년동기대비                        755.61
                    전분기대비                                184.95
당기순이익               컨센서스                               314258.0
                    잠정치                                     NaN
                    Surprise                                NaN
                    전분기대비보기전년동기대비                           NaN
                    전분기대비                                   NaN
잠정치발표(예정)일/회계기준     잠정치발표(예정)일/회계기준              2026/04/07(연결)

In [62]:
# sqlalchemy 
engine = create_engine(
    "mysql+pymysql://test_user:1234@localhost:3306/multicam"
)

In [63]:
df1.to_sql(
    name = 'table1', 
    con = engine
)

10

In [64]:
df2.to_sql(
    name = 'table2', 
    con = engine
)

12